### ISSUE TITLE
Moral vs Immoral labels for Visual Commonsense Immorality benchmark

### ISSUE THREAD

**Issue by teetone** [eugene6923/Zero-shot-Visual-Commonsense-Immorality-Prediction#1]
Thank you for sharing this benchmark! I see the link to the images at `data/VCI`, but I don't see the corresponding files indicating whether an image is immoral.

**Comment by eugene6923** [comment]
Thanks for your interest! The whole images contain immorality which has been highly curated by human being.

**Comment by teetone** [comment]
> Thanks for your interest! The whole images contain immorality which has been highly curated by human being.

Thanks for the quick reply! So, all the images in `data/VCI` are deemed immoral? I was a bit confused because, in figure 6 of the paper, the top row of images was classified as "Moral"? Are those images not included in the dataset folder `data/VCI`?

Figure 6:
![Screenshot 2022-12-28 at 9 09 15 PM](https://user-images.githubusercontent.com/16793796/209906248-e97f6dbc-6fef-4be7-aeaa-a803629eb647.png)

**Comment by eugene6923** [comment]
Those images are from ImageNet2014, which is used  in our paper for the inference! So yes, those images are not included in our dataset folder but you can see from ImageNet dataset :)

**Comment by teetone** [comment]
> Those images are from ImageNet2014, which is used in our paper for the inference! So yes, those images are not included in our dataset folder but you can see from ImageNet dataset :)

Sorry, I'm still a bit confused. From what's in `data/VCI`, it's unclear what the corresponding label is in ImageNet since it only has links to images.
For example, what are the corresponding moral images from ImageNet for the fly-tipping images: https://github.com/eugene6923/Zero-shot-Visual-Commonsense-Immorality-Prediction/blob/main/data/VCI/environmental%20pollution/fly-tipping.txt?

**Comment by eugene6923** [comment]
My apologies if our paper was unclear. Our dataset only consists of immoral images and those immoral images are under three categories (Felony, Antisocial Behavior, Environmental pollution). Each category has a number of classes (e.g. fly-tipping). The figure you presented above is just one result of how our model classifies immoral images in ImageNet. 

It was hard to define "moral" images so we instead assumed that COCO dataset was moral. And our human research (which is written in Section5) verifies that most of the images in the COCO dataset are moral. So I suggest using the COCO dataset as the images for the moral labels.

**Comment by teetone** [comment]
> My apologies if our paper was unclear. Our dataset only consists of immoral images and those immoral images are under three categories (Felony, Antisocial Behavior, Environmental pollution). Each category has a number of classes (e.g. fly-tipping). The figure you presented above is just one result of how our model classifies immoral images in ImageNet.
> 
> It was hard to define "moral" images so we instead assumed that COCO dataset was moral. And our human research (which is written in Section5) verifies that most of the images in the COCO dataset are moral. So I suggest using the COCO dataset as the images for the moral labels.

Okay, that makes sense. Thank you for your help! I will close this issue.
